# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamCode - v1.0.0 Beta"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO DreamCode"
welcomeDescription = ""
welcomeDescCTA = "Copyright © 2025 DreamCode"
